export type Tattoo = {
  id: string
  url: string
  title: string
  alt_text: string
  motivo: string
  zona: string
  tamaño: string
  tags: string[]
  tatuador: string
  tatuador_id: string
  likes: number
  height: number
  saves_count: number
  views_count: number
  ciudad: string
}

export const MOTIVOS = [
  'Floral', 'Geométrico', 'Minimalista', 'Animales', 'Letras',
  'Abstracto', 'Naturaleza', 'Símbolos', 'Retrato', 'Arquitectura'
]

export const ZONAS = [
  'Brazo', 'Antebrazo', 'Muñeca', 'Mano', 'Pierna', 'Tobillo',
  'Pie', 'Espalda', 'Pecho', 'Cuello', 'Detrás de la oreja', 'Costilla'
]

export const TAMAÑOS = ['Micro', 'Pequeño', 'Mediano', 'Grande']

export const tattoosSample: Tattoo[] = [
  {
    id: '1',
    url: 'https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=400&q=80',
    title: 'Rosa fine line en antebrazo',
    alt_text: 'Tatuaje fine line de rosa delicada en antebrazo, estilo minimalista',
    motivo: 'Floral',
    zona: 'Antebrazo',
    tamaño: 'Pequeño',
    tags: ['rosa', 'floral', 'fine line', 'delicado'],
    tatuador: 'Laura Ink',
    tatuador_id: 'laura-ink',
    likes: 243,
    height: 380,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '2',
    url: 'https://images.unsplash.com/photo-1562962230-16b140c0abea?w=400&q=80',
    title: 'Triángulo geométrico en muñeca',
    alt_text: 'Tatuaje geométrico de triángulo fine line en muñeca',
    motivo: 'Geométrico',
    zona: 'Muñeca',
    tamaño: 'Micro',
    tags: ['geometría', 'triángulo', 'minimalista'],
    tatuador: 'Marc Lines',
    tatuador_id: 'marc-lines',
    likes: 189,
    height: 300,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '3',
    url: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?w=400&q=80',
    title: 'Mariposa delicada en tobillo',
    alt_text: 'Tatuaje fine line de mariposa en tobillo, diseño delicado y elegante',
    motivo: 'Animales',
    zona: 'Tobillo',
    tamaño: 'Pequeño',
    tags: ['mariposa', 'animales', 'tobillo'],
    tatuador: 'Sofia Tattoo',
    tatuador_id: 'sofia-tattoo',
    likes: 412,
    height: 420,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '4',
    url: 'https://images.unsplash.com/photo-1590246814883-57c511e72e56?w=400&q=80',
    title: 'Luna y estrellas en cuello',
    alt_text: 'Tatuaje minimalista de luna creciente con estrellas en cuello',
    motivo: 'Símbolos',
    zona: 'Cuello',
    tamaño: 'Micro',
    tags: ['luna', 'estrellas', 'minimalista', 'cuello'],
    tatuador: 'Laura Ink',
    tatuador_id: 'laura-ink',
    likes: 567,
    height: 340,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '5',
    url: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=400&q=80',
    title: 'Serpiente en brazo',
    alt_text: 'Tatuaje fine line de serpiente enroscada en brazo',
    motivo: 'Animales',
    zona: 'Brazo',
    tamaño: 'Mediano',
    tags: ['serpiente', 'animales', 'brazo'],
    tatuador: 'Marc Lines',
    tatuador_id: 'marc-lines',
    likes: 334,
    height: 500,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '6',
    url: 'https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?w=400&q=80',
    title: 'Flor de cerezo en espalda',
    alt_text: 'Tatuaje fine line de flores de cerezo en espalda alta',
    motivo: 'Floral',
    zona: 'Espalda',
    tamaño: 'Grande',
    tags: ['cerezo', 'floral', 'japonés', 'espalda'],
    tatuador: 'Sofia Tattoo',
    tatuador_id: 'sofia-tattoo',
    likes: 891,
    height: 460,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '7',
    url: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&q=80',
    title: 'Coordenadas en muñeca',
    alt_text: 'Tatuaje de coordenadas geográficas en muñeca, letra fina',
    motivo: 'Letras',
    zona: 'Muñeca',
    tamaño: 'Pequeño',
    tags: ['coordenadas', 'letras', 'muñeca', 'minimalista'],
    tatuador: 'Ana Noir',
    tatuador_id: 'ana-noir',
    likes: 156,
    height: 280,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '8',
    url: 'https://images.unsplash.com/photo-1601645191163-3fc0d5d64e35?w=400&q=80',
    title: 'Montaña abstracta en antebrazo',
    alt_text: 'Tatuaje abstracto de silueta de montaña en antebrazo',
    motivo: 'Naturaleza',
    zona: 'Antebrazo',
    tamaño: 'Mediano',
    tags: ['montaña', 'naturaleza', 'abstracto'],
    tatuador: 'Marc Lines',
    tatuador_id: 'marc-lines',
    likes: 278,
    height: 360,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '9',
    url: 'https://images.unsplash.com/photo-1616698872122-9c98a9ee2d4e?w=400&q=80',
    title: 'Colibrí en detrás de la oreja',
    alt_text: 'Tatuaje fine line de colibrí detrás de la oreja',
    motivo: 'Animales',
    zona: 'Detrás de la oreja',
    tamaño: 'Micro',
    tags: ['colibrí', 'animales', 'oreja', 'delicado'],
    tatuador: 'Laura Ink',
    tatuador_id: 'laura-ink',
    likes: 723,
    height: 320,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '10',
    url: 'https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=400&q=80',
    title: 'Mandala en pierna',
    alt_text: 'Tatuaje fine line de mandala geométrico en muslo',
    motivo: 'Geométrico',
    zona: 'Pierna',
    tamaño: 'Grande',
    tags: ['mandala', 'geométrico', 'pierna'],
    tatuador: 'Ana Noir',
    tatuador_id: 'ana-noir',
    likes: 445,
    height: 480,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '11',
    url: 'https://images.unsplash.com/photo-1590246814883-57c511e72e56?w=400&q=80',
    title: 'Pluma en costilla',
    alt_text: 'Tatuaje fine line de pluma de ave en costilla',
    motivo: 'Naturaleza',
    zona: 'Costilla',
    tamaño: 'Mediano',
    tags: ['pluma', 'naturaleza', 'costilla'],
    tatuador: 'Sofia Tattoo',
    tatuador_id: 'sofia-tattoo',
    likes: 312,
    height: 400,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
  {
    id: '12',
    url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80',
    title: 'Sol y luna en mano',
    alt_text: 'Tatuaje dualidad sol y luna en mano, estilo fine line',
    motivo: 'Símbolos',
    zona: 'Mano',
    tamaño: 'Pequeño',
    tags: ['sol', 'luna', 'dualidad', 'símbolos', 'mano'],
    tatuador: 'Ana Noir',
    tatuador_id: 'ana-noir',
    likes: 598,
    height: 350,
    saves_count: 0,
    views_count: 0,
    ciudad: '',
  },
]

export const tatuadoresSample = [
  {
    id: 'laura-ink',
    nombre: 'Laura Ink',
    especialidad: 'Fine line floral',
    ciudad: 'Madrid',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    bio: 'Especialista en fine line con más de 6 años de experiencia. Diseños florales y minimalistas.',
    instagram: '@laura.ink',
    tattoos: tattoosSample.filter(t => t.tatuador_id === 'laura-ink'),
  },
  {
    id: 'marc-lines',
    nombre: 'Marc Lines',
    especialidad: 'Geométrico y abstracto',
    ciudad: 'Barcelona',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    bio: 'Fine line geométrico y abstracto. Cada tatuaje es único y diseñado a medida.',
    instagram: '@marc.lines',
    tattoos: tattoosSample.filter(t => t.tatuador_id === 'marc-lines'),
  },
  {
    id: 'sofia-tattoo',
    nombre: 'Sofia Tattoo',
    especialidad: 'Fine line naturaleza',
    ciudad: 'Valencia',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    bio: 'Apasionada de la naturaleza y el arte. Tatuajes de animales y flora en fine line.',
    instagram: '@sofia.tattoo',
    tattoos: tattoosSample.filter(t => t.tatuador_id === 'sofia-tattoo'),
  },
  {
    id: 'ana-noir',
    nombre: 'Ana Noir',
    especialidad: 'Minimalista y letras',
    ciudad: 'Sevilla',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80',
    bio: 'Lettering y diseños minimalistas. Tatuajes con significado para toda la vida.',
    instagram: '@ana.noir',
    tattoos: tattoosSample.filter(t => t.tatuador_id === 'ana-noir'),
  },
]
