// Bidirectional tag synonyms — EN ↔ ES
// When a user searches "flower" → also search "floral", and vice versa.
const SYNONYMS: Record<string, string[]> = {
  // Florals
  flower:      ['floral', 'flores', 'flor'],
  flowers:     ['floral', 'flores', 'flor'],
  floral:      ['flower', 'flowers', 'flores', 'flor'],
  flor:        ['floral', 'flower', 'flowers', 'flores'],
  flores:      ['floral', 'flower', 'flowers', 'flor'],
  rose:        ['rosa', 'rosas'],
  roses:       ['rosa', 'rosas'],
  rosa:        ['rose', 'roses'],

  // Nature
  moon:        ['luna'],
  luna:        ['moon'],
  butterfly:   ['mariposa', 'mariposas'],
  mariposa:    ['butterfly', 'butterflies'],
  snake:       ['serpiente', 'víbora'],
  serpiente:   ['snake'],
  bird:        ['pájaro', 'ave', 'pájaros'],
  pájaro:      ['bird', 'birds'],
  tiger:       ['tigre'],
  tigre:       ['tiger'],
  dragon:      ['dragón'],
  dragón:      ['dragon'],
  wolf:        ['lobo'],
  lobo:        ['wolf'],
  cat:         ['gato', 'gatos'],
  gato:        ['cat', 'cats'],
  fish:        ['pez', 'peces'],
  pez:         ['fish'],
  leaf:        ['hoja', 'hojas'],
  hoja:        ['leaf', 'leaves'],
  tree:        ['árbol', 'árboles'],
  árbol:       ['tree', 'trees'],
  mushroom:    ['seta', 'setas', 'hongo'],
  seta:        ['mushroom', 'mushrooms'],
  bee:         ['abeja', 'abejas'],
  abeja:       ['bee', 'bees'],
  spider:      ['araña', 'arañas'],
  araña:       ['spider', 'spiders'],

  // Style
  minimalist:  ['minimalista', 'minimalismo'],
  minimalistic:['minimalista', 'minimalismo'],
  minimalista: ['minimalist', 'minimalistic'],
  geometric:   ['geométrico', 'geometría'],
  geometrico:  ['geometric', 'geometry'],
  geométrico:  ['geometric', 'geometry'],
  blackwork:   ['negro', 'black'],
  dotwork:     ['puntillismo', 'puntos'],
  puntillismo: ['dotwork'],
  watercolor:  ['acuarela'],
  acuarela:    ['watercolor', 'watercolour'],
  fineline:    ['fine line', 'fine-line', 'linea fina'],
  'fine line': ['fineline', 'fine-line', 'linea fina'],

  // Body areas
  arm:         ['brazo', 'brazos'],
  brazo:       ['arm'],
  leg:         ['pierna', 'piernas'],
  pierna:      ['leg', 'legs'],
  back:        ['espalda'],
  espalda:     ['back'],
  chest:       ['pecho'],
  pecho:       ['chest'],
  neck:        ['cuello', 'nuca'],
  cuello:      ['neck'],
  wrist:       ['muñeca', 'muñecas'],
  muñeca:      ['wrist', 'wrists'],
  ankle:       ['tobillo', 'tobillos'],
  tobillo:     ['ankle', 'ankles'],
  shoulder:    ['hombro', 'hombros'],
  hombro:      ['shoulder', 'shoulders'],
  finger:      ['dedo', 'dedos'],
  dedo:        ['finger', 'fingers'],
  hand:        ['mano', 'manos'],
  mano:        ['hand', 'hands'],
  rib:         ['costilla', 'costillas'],
  costilla:    ['rib', 'ribs'],
  spine:       ['columna', 'espina'],
  columna:     ['spine'],

  // Common motifs
  star:        ['estrella', 'estrellas'],
  stars:       ['estrella', 'estrellas'],
  estrella:    ['star', 'stars'],
  sun:         ['sol'],
  sol:         ['sun'],
  cloud:       ['nube', 'nubes'],
  nube:        ['cloud', 'clouds'],
  wave:        ['ola', 'olas'],
  ola:         ['wave', 'waves'],
  heart:       ['corazón'],
  corazón:     ['heart'],
  skull:       ['calavera', 'calaveras'],
  calavera:    ['skull', 'skulls'],
  crown:       ['corona'],
  corona:      ['crown'],
  sword:       ['espada'],
  espada:      ['sword'],
  feather:     ['pluma'],
  pluma:       ['feather'],
  eye:         ['ojo', 'ojos'],
  ojo:         ['eye', 'eyes'],
  diamond:     ['diamante'],
  diamante:    ['diamond'],
  anchor:      ['ancla'],
  ancla:       ['anchor'],
  compass:     ['brújula'],
  brújula:     ['compass'],
  clock:       ['reloj', 'relojes'],
  reloj:       ['clock', 'watch'],
  key:         ['llave'],
  llave:       ['key'],
  fox:         ['zorro'],
  zorro:       ['fox'],
  owl:         ['búho'],
  búho:        ['owl'],
  deer:        ['ciervo', 'venado'],
  ciervo:      ['deer'],

  // Letters / scripts
  letters:     ['letras', 'tipografía', 'caligrafía'],
  letras:      ['letters', 'typography', 'calligraphy'],
  script:      ['letras', 'caligrafía'],
  calligraphy: ['caligrafía', 'letras'],
  caligrafía:  ['calligraphy', 'letters'],

  // Mandala / spiritual
  mandala:     ['mandala'],
  lotus:       ['loto'],
  loto:        ['lotus'],

  // Animals
  animals:     ['animales'],
  animales:    ['animals'],
  elephant:    ['elefante'],
  elefante:    ['elephant'],
  lion:        ['león'],
  león:        ['lion'],
  bear:        ['oso'],
  oso:         ['bear'],
}

/**
 * Expand a search query with synonyms.
 * Returns the original query + any known synonyms as an array of terms.
 */
export function expandQuery(query: string): string[] {
  const normalized = query.toLowerCase().trim()
  const synonyms = SYNONYMS[normalized] ?? []
  return [normalized, ...synonyms]
}
// build trigger
